Add commit tag job
equinix-labs/terraform-equinix-template pull request #10
Opened 2023-02-24 23:13 UTC by dcallao

This PR adds a manual GitHub action to tag a commit with a valid semantic version. See: https://github.com/marketplace/actions/create-tag

2023-02-27 18:59 UTC, ctreatma requested changes
This seems like this includes the changes from #8; am I reading it correctly?  If so, marking this PR as "Request changes" until the other one is merged & this one can be rebased.

2023-02-27 20:24 UTC, dcallao commented
@ctreatma I have rebased to latest in `main` branch.

2023-02-28 19:59 UTC, ctreatma commented
It looks like this PR still includes some changes that have been merged to `main` in other PRs.  Could you double-check that you force-pushed the PR branch after rebasing?

2023-02-28 22:41 UTC, dcallao commented
@ctreatma So it turns out Im having problems with Zscaler, it is blocking my SSH access to git hence the rebase issue. I think I got Zscaler to allow the git ssh connection. Would you have a look when you have a moment?

2023-03-01 15:17 UTC, ctreatma commented
I think this would benefit from some documentation in the `README`.  Am I understanding correctly that the purpose of this job is to add validation to tags to ensure they are in semver format?  Is the expectation that all tags on this repo should go through this workflow and be valid semver tags, or is this intended to be used in specific circumstances?

2023-03-02 21:37 UTC, dcallao commented
@ctreatma From our discussion over Zoom, this PR does not accomplish what we would like to do here - build automation commit tag, release, and changelog. I will submit a new PR to address the goal accordingly.

2023-03-02 21:37 UTC, closed without merging